@startuml
title Replay Aggregate Report
actor "System Operator" as Operator
database DLC as DLC
participant Dhis2RapidPro as Dhis2RapidPro
queue Queue as Queue
autonumber
skinparam responseMessageBelowArrow true
activate Dhis2RapidPro
activate Operator
Operator -> DLC: Update failed rows to 'RETRY'
return
deactivate Operator
loop every 5s
    autonumber
    Dhis2RapidPro -> DLC: Select rows where status is 'RETRY'
    DLC --> Dhis2RapidPro: Rows
    loop rows
        Dhis2RapidPro -> Queue: Enqueue webhook message
        Dhis2RapidPro -> DLC: Update row status to 'PROCESSED'
    end
end
@enduml