@startuml
title Transfer Aggregate Report
participant Dhis2RapidPro as Dhis2RapidPro
queue Queue as Queue
participant DHIS2 as DHIS2
participant RapidPro as RapidPro
database DLC as DLC
autonumber
skinparam responseMessageBelowArrow true
header
    1. dataElements.json
    2. dataSets.json
    3. dataValueSet.json
endheader

loop
    alt
        Dhis2RapidPro -> Queue: Dequeue
        Queue --> Dhis2RapidPro: Webhook message
        note over Dhis2RapidPro: Read data set code from webhook message
        Dhis2RapidPro -> DHIS2: Fetch data elements by data set code [1]
        DHIS2 --> Dhis2RapidPro: Data set data elements
        alt
            note over Dhis2RapidPro: Read org unit ID from webhook message
        else org unit ID is missing
            note over Dhis2RapidPro: Read contact UUID from webhook message
            Dhis2RapidPro -> RapidPro: [[https://rapidpro.io/api/v2/contacts Fetch contact by UUID]]
            RapidPro --> Dhis2RapidPro: Contact
            note over Dhis2RapidPro: Read org unit ID from contact
        end
        Dhis2RapidPro -> DHIS2: Fetch data set by code [2]
        DHIS2 --> Dhis2RapidPro: Data set
        note over Dhis2RapidPro: Read period type from data set
        alt
            note over Dhis2RapidPro: Read report period offset from webhook message
         else report period offset is missing
           note over Dhis2RapidPro: Assume report period offset is -1
        end
        note over Dhis2RapidPro: Compute report period from period type & period offset
        note over Dhis2RapidPro: Assemble data value set & soft validate DHIS2 identifiers
        Dhis2RapidPro -> DHIS2: Create data value set [3]
    else exception
        Dhis2RapidPro -> DLC: Save webhook message
    end
end
@enduml
