name: Generate UML diagrams

on:
  push:
    branches: [ main ]

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ts-graphviz/setup-graphviz@v1
      - run: curl -LJ https://github.com/plantuml/plantuml/releases/download/v1.2022.7/plantuml-1.2022.7.jar -o plantuml.jar
      - run: java -jar plantuml.jar -v -tpng -r design/plantuml/**.puml -o ../../static/images
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: generate UML diagrams'
          file_pattern: 'static/images/*.png'
